services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=servidores_db
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - MINIO_ENDPOINT=http://minio.seletivo-seplag.mt.gov.br:9000
      - MINIO_KEY=minioadmin
      - MINIO_SECRET=minioadmin
      - MINIO_BUCKET=servidores
    networks:
      - backend
    depends_on:
      - db
      - minio

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: servidores_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio-storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - backend
    ports:
      - "9000:9000"
      - "9001:9001"

  webserver:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - backend
    depends_on:
      - app

volumes:
  postgres_data:
  minio_data:

networks:
  backend:
    driver: bridge
